version: "2.24"

services:
  helloworld-project:
    image: "helloworld-project"
    build:
      context: ./modules/helloworld-project/
      dockerfile: Dockerfile
    environment:
      HELLOWORLD_USER_NAME: "Dmitry"

  bookstore-book:
    image: "book-service"
    build:
      context: ./modules/book-service/
      dockerfile: Dockerfile
    environment:
      # Forwarding some environments variables from `.env` file
      # to our (Java-based) service environment variables when service will be start
      # It environments will be used within `application.yml`
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}

      JAVA_TOOL_OPTIONS: "-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005"
    ports:
      - "80:8080"
      - "5005:5005"
    # Spring service must be start after postgres DB service
    depends_on:
      bookstore-postgres:
        condition: service_healthy
    networks:
      - common-bookstore-network

  bookstore-postgres:
    image: "postgres:16.1"
    ports:
      - "5432:5432"
    environment:
      # Put environment variable from `.env` file to service env. variables
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      PGDATA: /var/lib/postgresql/data/pgdata
    networks:
      - common-bookstore-network
    healthcheck:
      test: "pg_isready -U postgres"
      start_period: 10s
      interval: 5s
      retries: 5
    volumes:
      - book-store-pg-data:/var/lib/postgresql/data

networks:
  common-bookstore-network:

volumes:
  book-store-pg-data: