hello-message: "Привет!!!"
spring:
  datasource:
    #Connection address may be directly or service name from docker-compose
    url: jdbc:postgresql://bookstore-postgres:5432/bookstore
    username: postgres
    password: 12345
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy
